import { getSession } from '@auth0/nextjs-auth0';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { redirect } from 'next/navigation';
import type { Metadata } from 'next';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Wikimap',
  description: 'Generated by Wikimap',
};

interface Props {
  readonly children: React.ReactNode;
  readonly params: {
    readonly id: string;
  };
}

export default async function RootLayout({ children, params }: Props) {
  const session = await getSession();

  if (session === undefined || session === null) {
    redirect('/');
  }

  return (
    <html lang='ja' data-theme='corporate'>
      <UserProvider>
        <body>{children}</body>
      </UserProvider>
    </html>
  );
}
