name: PR Check

env:
  TZ: 'Asia/Tokyo'

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    # コミットメッセージに[skip ci]がある場合は、CIを回さない
    if: ${{ !contains(github.event.commits.*.message, '[skip ci]') }}

    steps:
      - uses: actions/checkout@v4

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Tokyo'
          timezoneMacos: 'Asia/Tokyo'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Check Lint
        run: bun run lint

      # - name: Check Test
      #   run: bun run test

      - name: Check Build
        run: bun run build
